### ISSUE TITLE
关于Warmup-Java-02中两个与其他不一样的project编译或运行失败

### ISSUE THREAD

**Issue by nju-zzp** [XZ-X/2020SE1-FAQ#1]
warmup02中题目order-string和left-rotate-string，最开始clone下来与其他的题目不同，多了一些“不正常”的文件，于是我把看起来没用的文件删掉，文件目录与其他题目保持相同，最后在本地运行test全过，但是push后编译或运行失败。不知这是什么原因？（本地的jdk也是1.8)
![image](https://user-images.githubusercontent.com/61078279/81581728-b44b9b80-93e1-11ea-92b9-46b2fe30cf5c.png)
![image](https://user-images.githubusercontent.com/61078279/81581850-e1984980-93e1-11ea-8d60-ce3a87475d8e.png)
![image](https://user-images.githubusercontent.com/61078279/81581885-eeb53880-93e1-11ea-9a24-da61086f8296.png)
![image](https://user-images.githubusercontent.com/61078279/81581907-f4ab1980-93e1-11ea-9f9e-e83862c40bbe.png)
![image](https://user-images.githubusercontent.com/61078279/81581970-0c829d80-93e2-11ea-8be3-7e47a76d4fe7.png)

**Comment by XZ-X** [comment]
已反馈，在有答复之前也可以试着问一下已经通过的同学是怎么操作的～

**Comment by XZ-X** [comment]
来自平台助教：检查一下是不是OrderString.java里有`package`语句？把所有的`package`语句都删掉再试试？

**Comment by nju-zzp** [comment]
好的谢谢助教啦！

**Comment by nju-zzp** [comment]
好的谢谢助教啦！

**Comment by XZ-X** [comment]
所以去掉`package`能解决问题嘛？

**Comment by nju-zzp** [comment]
唉可惜不行啊 文件的开始是import语句 然后就是public class了 我这就去问问同学 应该可以解决的 哈哈谢谢热心的助教啦

**Comment by XZ-X** [comment]
Orz也可以直接去找相关的平台助教问一下（群里的“mooc负责助教”） 
good luck！
