### ISSUE TITLE
有关win10系统ZipFile中ZipEntry的getName()方法 （ZipFile中getEntry()同理)

### ISSUE THREAD

**Issue by nju-zzp** [XZ-X/2020SE1-FAQ#10]
问题：zipEntry.getName() 返回的是 "java/lang/Object.class"，分隔符为正斜杠'/'
           文件路径并不是用File.seperator 即 '\' 分隔
           但是非zip的文件路径调用File.seperator依然是'\'
           因此不能直接将zipEntry的name与classname进行比较
寻找原因：
https://docs.microsoft.com/zh-cn/dotnet/framework/migration-guide/mitigation-ziparchiveentry-fullname-path-separator
![image](https://user-images.githubusercontent.com/61078279/81849173-bef46500-9588-11ea-8ed5-b18761f154e2.png)
问：大家是否有类似问题？还是我自己并不需要纠结此问题就可以解决？

**Comment by wym0120** [comment]
做个简单的转换就好了，可以看一下transform方法的实现。这样就可以同时应对新旧版本的问题了
