### ISSUE TITLE
JVM02

### ISSUE THREAD

**Issue by yuzhouzhao** [XZ-X/2020SE1-FAQ#12]
![image](https://user-images.githubusercontent.com/65386200/82016019-a84a2d00-96b2-11ea-95aa-cfa08ec33d18.png)
出现了这个错误，但代码成功ac了。报错为重复关闭流，是本来就有的IO代码的问题吗

**Comment by XZ-X** [comment]
不确定，不过从我目前的判断来说，应该不是本来IO代码的问题？你的实现代码在哪里关闭了文件了嘛？

**Comment by wym0120** [comment]
IO类没有问题，很多同学都可以AC（我也自己试过了）。或许是你的使用方法里不小心忽略了某个细节。当然你也可以自己写IO的。这部分本身不会作为接口暴露给测试，所以可以随便改，只要别把原来的类删除掉就行，因为服务器可能会报错
