### ISSUE TITLE
关于filenotfound

### ISSUE THREAD

**Issue by growingrookie** [XZ-X/2020SE1-FAQ#15]
![屏幕快照 2020-05-17 下午11 47 48](https://user-images.githubusercontent.com/58394997/82153248-e6a14100-9898-11ea-9e24-304aafb475e0.png)
ArchivedEntry 的testsuccess一直报这个错，debug以后发现不存在这个文件，是因为classpath和classname间的分隔符有问题吗？下附代码
![屏幕快照 2020-05-17 下午11 52 30](https://user-images.githubusercontent.com/58394997/82153347-7ba43a00-9899-11ea-98bd-9d7d5b208598.png)

**Comment by XZ-X** [comment]
( ´▽` )ﾉ请参考生存手册自行debug喔
