### ISSUE TITLE
关于UTF8info中的getInstance方法

### ISSUE THREAD

**Issue by lollipop190** [XZ-X/2020SE1-FAQ#16]
![D{B~I _5XL183OIXA%6FZ%L](https://user-images.githubusercontent.com/58462846/82425168-bafca180-9ab8-11ea-82c3-8600ae73afdb.png)
从图中可以清晰的看到这个getInstance方法没有用到。。。助教可以解释一下是我理解错了还是其他问题吗？

**Comment by wym0120** [comment]
没用到也没有问题的，这个是老师加的方法。你可以使用pair去返回，当然也可以通过别的方法返回。测试里没有直接或者间接调用到的接口都是可以修改的

**Comment by lollipop190** [comment]
emm那怎么检验我这个方法写的对不对呢?说实话我感觉我写的不对

**Comment by XZ-X** [comment]
@wym0120 的意思是，这个方法是原有系统中为了正确解析常量池的一种实现方式；如果你使用别的方式来实现，可以不用管这个方法。而如果你使用了这个方法来实现，那么只要能正确通过关于常量池的测试用例，就说明实现正确啦( ´▽` )ﾉ

**Comment by wym0120** [comment]
> emm那怎么检验我这个方法写的对不对呢?说实话我感觉我写的不对

你可以使用一些assert语句来验证，或者自己加一些简单的测试。想要做到绝对没有错，那不是通过测试来完成的，应该借助更形式化的东西。测试是修复错误的过程，但不能说通过测试用例就一定没有bug存在
