### ISSUE TITLE
第二次大作业本地能过远端编译失败

### ISSUE THREAD

**Issue by growingrookie** [XZ-X/2020SE1-FAQ#17]
![屏幕快照 2020-05-20 下午11 02 50](https://user-images.githubusercontent.com/58394997/82463057-f0bc7d00-9aee-11ea-82e3-9c634c1ffa65.png)
![屏幕快照 2020-05-20 下午11 09 35](https://user-images.githubusercontent.com/58394997/82463112-0336b680-9aef-11ea-8735-4a3458aa5215.png)

**Comment by XZ-X** [comment]
把控制台错误完整贴出来呀QAQ

**Comment by growingrookie** [comment]
不好意思好像图裂了q w q

**Comment by growingrookie** [comment]
![屏幕快照 2020-05-20 下午11 13 34](https://user-images.githubusercontent.com/58394997/82463583-996adc80-9aef-11ea-8fb9-de297ff0dba9.png)
![屏幕快照 2020-05-20 下午11 13 41](https://user-images.githubusercontent.com/58394997/82463589-9b34a000-9aef-11ea-9b43-91f09493941d.png)
![屏幕快照 2020-05-20 下午11 13 48](https://user-images.githubusercontent.com/58394997/82463597-9c65cd00-9aef-11ea-8c18-fae582b9220f.png)

**Comment by XZ-X** [comment]
不不 我能看到你发了两个图，但是第二个图好像没截完( ´▽` )ﾉ

**Comment by XZ-X** [comment]
你改动测试文件了嘛？看起来你的代码多抛出了一个异常，但是原来的方法声明上没有？

**Comment by growingrookie** [comment]
在ide上写的时候不知道什么时候改过，之后又改成和seec上一样的了，提交前已经检查过一致

**Comment by XZ-X** [comment]
试着百度一下你第二个截图里的ERROR看看有没有你对应的情况喔

**Comment by growingrookie** [comment]
还是不太明白，我的方法有throw啊,调用的方法也有throw异常，不知道该怎么改
![屏幕快照 2020-05-20 下午11 33 03](https://user-images.githubusercontent.com/58394997/82465951-65dd8180-9af2-11ea-92a3-b6ab7e81524e.png)

**Comment by growingrookie** [comment]
解决了，是复制的时候丢失代码了....麻烦助教了，非常感谢！
