### ISSUE TITLE
本地通过线上无法通过testCompositeSuccess

### ISSUE THREAD

**Issue by mircop1t** [XZ-X/2020SE1-FAQ#19]
![Microsoft Edge 2020_5_27 1_18_51](https://user-images.githubusercontent.com/65972014/82965387-8c238580-9ffa-11ea-8a58-5113df57ce17.png)
![Screenshot 2020_5_27 1_18_13](https://user-images.githubusercontent.com/65972014/82965393-904fa300-9ffa-11ea-8cea-c655433bea54.png)

![Microsoft Edge 2020_5_27 1_18_39](https://user-images.githubusercontent.com/65972014/82965367-7d3cd300-9ffa-11ea-9bfd-01237ec6bb6b.png)

**Comment by wym0120** [comment]
你可以先检查一下有没有系统分隔符的问题。这也有可能是服务器的问题，我已经帮你联系mooc的助教了

**Comment by mircop1t** [comment]
我所有出现的路径都用transform包起来了，但还是这样报错...

**Comment by mircop1t** [comment]
求助求助，马上就要截止了QAQ 我把所有分隔符都换了还是过不了

**Comment by XZ-X** [comment]
学号？

**Comment by mircop1t** [comment]
191250143

**Comment by XZ-X** [comment]
经核实你的实现有平台相关的地方，仔细读手册再试试看( ´▽` )ﾉ加油！

**Comment by mircop1t** [comment]
嗯嗯我再看看 谢谢助教了
