### ISSUE TITLE
问一个奇怪的问题，为什么我的github网页端突然变成了这个样子？

### ISSUE THREAD

**Issue by Gxy-2001** [XZ-X/2020SE1-FAQ#2]
这是网页端，好像从昨天开始的。
我是个菜鸡，仅仅尝试了 重启 和 清除浏览数据 ，没效果  
![github](https://user-images.githubusercontent.com/56917631/81632499-0968cb00-943d-11ea-9a4d-bbf7ace9b5fd.png)

**Comment by XZ-X** [comment]
试着调一下缩放比例？比如在Chrome里按一下`control`(macOS为`command`)+`0`

**Comment by Gxy-2001** [comment]
问题解决，自己是个傻子，可能不小心按到了吧
