### ISSUE TITLE
大作业五本地过前三个用例 网站编译失败

### ISSUE THREAD

**Issue by growingrookie** [XZ-X/2020SE1-FAQ#23]
![屏幕快照 2020-06-07 下午2 27 26](https://user-images.githubusercontent.com/58394997/83962027-ee6a6900-a8cb-11ea-9073-db34beb8ecfd.png)
![屏幕快照 2020-06-07 下午2 27 32](https://user-images.githubusercontent.com/58394997/83962031-f88c6780-a8cb-11ea-88b2-b3e7a9402343.png)
![屏幕快照 2020-06-07 下午2 27 50](https://user-images.githubusercontent.com/58394997/83962032-ffb37580-a8cb-11ea-8687-5d491c0d48bc.png)

**Comment by XZ-X** [comment]
学号？

**Comment by growingrookie** [comment]
191250094

**Comment by XZ-X** [comment]
收到( ´▽` )ﾉ 已提交给平台助教处理 
多谢反馈！

**Comment by growingrookie** [comment]
谢谢助教xgg

**Comment by XZ-X** [comment]
重新提交一下试试看

**Comment by growingrookie** [comment]
可以了，谢谢～
