### ISSUE TITLE
大作业6中，为要调用的方法创建新栈帧时的问题。

### ISSUE THREAD

**Issue by BZ-D** [XZ-X/2020SE1-FAQ#25]
局部变量表Vars在invokeinterface时，Vars此类已经有setObjectref方法了，也有setSlot方法，为什么在Vars索引值0的地方存储Objectref时先存入槽slot中进而使用setSlot而非直接用setObjectref方法来存放呢？求解

**Comment by XZ-X** [comment]
我觉得都可以？
