### ISSUE TITLE
为调用的方法创建新栈帧时，局部变量表的问题

### ISSUE THREAD

**Issue by BZ-D** [XZ-X/2020SE1-FAQ#26]
新创建的栈帧里局部变量表存储顺序和原栈帧局部变量表的存储顺序为什么截然相反呢？
![1](https://user-images.githubusercontent.com/67549719/85981582-050d6700-ba17-11ea-8c45-5ef286a1d706.png)
![2](https://user-images.githubusercontent.com/67549719/85981591-08085780-ba17-11ea-95ce-3c20d6e4ea3b.png)

**Comment by XZ-X** [comment]
考虑一下不同数据结构的特征，或试着画个图来思考一下
