### ISSUE TITLE
大作业Final在线修改后，本地pull发现测试的.class文件全部改变无法读取

### ISSUE THREAD

**Issue by Holloworlds** [XZ-X/2020SE1-FAQ#27]
前期一直是本地push代码，之后在线删除一行代码进行测试后又重新添加回去。代码与本地相同。本地显示版本落后无法push，pull代码后发现.class文件全部改变，原因不明
![01](https://user-images.githubusercontent.com/57065044/87551452-fa272780-c6e2-11ea-8cb0-e9d254abf5e0.png)
现在本地读取.class文件会报错
![02](https://user-images.githubusercontent.com/57065044/87551660-44100d80-c6e3-11ea-9cde-f51c1c96da5d.png)

**Comment by XZ-X** [comment]
学号发一下喔

**Comment by Holloworlds** [comment]
我刚把远端覆盖了，现在解决了，谢谢老师
