### ISSUE TITLE
运行test出现错误，reimport没用

### ISSUE THREAD

**Issue by cleardirt** [XZ-X/2020SE1-FAQ#4]
Error:(23, 9) java: 找不到符号
  符号:   类 ClassFile
  位置: 类 edu.nju.ClassFileReaderTest
Error:(4, 38) java: 程序包seec.test.util.classfileparser不存在
Error:(23, 35) java: 找不到符号
  符号:   类 ClassFile
  位置: 类 edu.nju.ClassFileReaderTest

**Comment by XZ-X** [comment]
问题收到 正在调查

**Comment by XZ-X** [comment]
代码有没有出现编译不通过的地方呢？如果有，IDE给的错误提示是啥？

**Comment by wym0120** [comment]
尝试搜索一下maven IDEA cannot find symbol这样的关键字，猜测是你的maven路径没有配置正确

**Comment by cleardirt** [comment]
> 代码有没有出现编译不通过的地方呢？如果有，IDE给的错误提示是啥？

没写代码直接运行的test，想试试能不能正常运行

**Comment by cleardirt** [comment]
> 尝试搜索一下maven IDEA cannot find symbol这样的关键字，猜测是你的maven路径没有配置正确

路径看的感觉是没错的啊，是不是路径含有中文名的原因，可是我用另外下载的maven在全英文路径下也是这样。。。

**Comment by XZ-X** [comment]
在之前的作业中maven可以正常使用吗？

**Comment by cleardirt** [comment]
> 在之前的作业中maven可以正常使用吗？

刚才试着让同学把依赖包拷过来就能用了，看来是maven下载不了的问题了

**Comment by cleardirt** [comment]
之前的作业也不能用，有些小作业是自己加的依赖才能用

**Comment by XZ-X** [comment]
👌

**Comment by XZ-X** [comment]
> 之前的作业也不能用，有些小作业是自己加的依赖才能用

那你的maven可能没有配置好，建议联系同学或百度重新配置一下
