### ISSUE TITLE
大作业02 pom文件reimport后无反应

### ISSUE THREAD

**Issue by zijunchen68** [XZ-X/2020SE1-FAQ#5]
无法通过reimport下载依赖

**Comment by zijunchen68** [comment]
大作业01是可以正常下载的

> 无法通过reimport下载依赖

**Comment by XZ-X** [comment]
试一下在命令行里输入`mvn compile` 看看有没有报错信息？

**Comment by zijunchen68** [comment]
> 试一下在命令行里输入`mvn compile` 看看有没有报错信息？

有warning 但是正在下载
WARNING:
Some problems were encountered while building the effective model for edu.nju:class-file-reader:jar:1.0
'dependencies.dependency.systemPath' for seec.test.util:parser:jar should not point at files within the project directory, ${project.basedir}/src/test/libs/parser.jar will be unresolvable by dependent projects @ line 45, column 25
'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 9, column 21

It is highly recommended to fix these problems because they threaten the stability of your build.

For this reason, future Maven versions might no longer support building such malformed projects.

**Comment by XZ-X** [comment]
maven本身应该没问题，等它下载就好了

BTW, 
@wym0120 这个warning是不是找不到parser.jar的原因？

**Comment by zijunchen68** [comment]
> maven本身应该没问题，等它下载就好了
> 
> BTW,
> @wym0120 这个warning是不是找不到parser.jar的原因？

BUILD SUCCESS之后打开IDEA好像还是会显示没有依赖o(╥﹏╥)o

**Comment by wym0120** [comment]
BUILD SUCCESS 运行测试会报Null Pointer Exception吗

> > maven本身应该没问题，等它下载就好了
> > BTW,
> > @wym0120 这个warning是不是找不到parser.jar的原因？
> 
> BUILD SUCCESS之后打开IDEA好像还是会显示没有依赖o(╥﹏╥)o

**Comment by zijunchen68** [comment]
> BUILD SUCCESS 运行测试会报Null Pointer Exception吗
> 
> > > maven本身应该没问题，等它下载就好了
> > > BTW,
> > > @wym0120 这个warning是不是找不到parser.jar的原因？
> > 
> > 
> > BUILD SUCCESS之后打开IDEA好像还是会显示没有依赖o(╥﹏╥)o

我重新clone了下文件再compile就好了，谢谢助教

**Comment by wym0120** [comment]
> > BUILD SUCCESS 运行测试会报Null Pointer Exception吗
> > > > maven本身应该没问题，等它下载就好了
> > > > BTW,
> > > > @wym0120 这个warning是不是找不到parser.jar的原因？
> > > 
> > > 
> > > BUILD SUCCESS之后打开IDEA好像还是会显示没有依赖o(╥﹏╥)o
> 
> 我重新clone了下文件再compile就好了，谢谢助教

在你import maven项目之后，IDEA右下角会提示enable auto-import，一般直接enable就可以解决依赖问题了。实验愉快 xD
