### ISSUE TITLE
请问为什么在idea和oj上运行结果不同呢

### ISSUE THREAD

**Issue by Gxy-2001** [XZ-X/2020SE1-FAQ#6]
![image](https://user-images.githubusercontent.com/56917631/81778601-c33b6680-9525-11ea-813e-a48c39265b4f.png)
![image](https://user-images.githubusercontent.com/56917631/81778625-cd5d6500-9525-11ea-8f56-c9d84292f95e.png)
![image](https://user-images.githubusercontent.com/56917631/81778680-dd754480-9525-11ea-9119-6738082a5d6f.png)
之前我在本地过了之后，第一次交到网上居然有一半挂了
提示的错误是空指针，位置就在这
![image](https://user-images.githubusercontent.com/56917631/81778754-ff6ec700-9525-11ea-9706-20aaf7d8b603.png)
我在本地没问题，就加了判断是不是null的if，就变成上面那样了
感觉网站上的 fs数组都是null，但是我不会解决

**Comment by wym0120** [comment]
terminal里执行一下mvn test的结果是什么

**Comment by Gxy-2001** [comment]
em...说实话我不会终端执行，我是fiveε(┬┬﹏┬┬)3

**Comment by wym0120** [comment]
![image](https://user-images.githubusercontent.com/26080950/81782881-11079d00-952d-11ea-9798-5931f5037f3c.png)

**Comment by XZ-X** [comment]
学一下( ´▽` )ﾉ 使用terminal挺重要的，因为可以看到更多的错误提示等信息

**Comment by Gxy-2001** [comment]
我现在应该是确定没有分隔符的问题了，本地mvn test还是能过，oj上还是过不去

**Comment by wym0120** [comment]
你在第三张截图里面的报错是什么，是不是IOException被你catch掉了

**Comment by Gxy-2001** [comment]
![image](https://user-images.githubusercontent.com/56917631/81787573-d6553300-9533-11ea-952c-8cd94d26a159.png)
![image](https://user-images.githubusercontent.com/56917631/81787620-e79e3f80-9533-11ea-89ef-e767552d1839.png)
这.....啥意思

**Comment by XZ-X** [comment]
解决了吗？

**Comment by Gxy-2001** [comment]
我自己解决的！过了三个小时我才意识到要去看OJ上的控制台输出

**Comment by XZ-X** [comment]
棒👍

**Comment by Gxy-2001** [comment]
Linux居然TM的区分大小写，我为了方便直接replaceALL("JAR","jar")了，Linux居然不识别，这个玩意卡了我三个小时
