### ISSUE TITLE
为什么会有图中标识的原因导致编译失败

### ISSUE THREAD

**Issue by yuan-su-xuan** [XZ-X/2020SE1-FAQ#7]
![picture](https://user-images.githubusercontent.com/56704201/81791040-c7bd4a80-9538-11ea-8ec0-d6cc82ea5984.PNG)

**Comment by wym0120** [comment]
这个warning并不会导致你编译失败，本地能跑过吗，或者OJ控制台还有其他什么报错信息吗

**Comment by yuan-su-xuan** [comment]
本地是可以跑过的，只是上传seec后就编译失败了
这是其他的报错
![图片](https://user-images.githubusercontent.com/56704201/81799536-0b698180-9544-11ea-8210-b259d98582fb.png)
![图片](https://user-images.githubusercontent.com/56704201/81799592-23410580-9544-11ea-8ef3-012c1839141b.png)

**Comment by wym0120** [comment]
你的ArchivedEntry.java的[3,34]位置使用了一个服务器没有的依赖，你看是不是你import的时候选错类了。如果你确定要使用这个类的话就换一种实现，不要增加新的依赖。

**Comment by yuan-su-xuan** [comment]
哦哦！感谢助教gg！

**Comment by wym0120** [comment]
> 哦哦！感谢助教gg！

~

**Comment by kenny67nju** [comment]
这个是Warning，看看Error是啥？
