### ISSUE TITLE
有关java.nio.BufferUnderflowException的异常

### ISSUE THREAD

**Issue by FredNggg** [XZ-X/2020SE1-FAQ#8]
这是我在处理DirEntry时用例发出的报错...在网上查找了很久的原因了，也找不到适合我的解决方案。以及debug发现问题大概出在inputstream的处理上面。但是我怎么改都会报错...不得已上来求助QAQ 
![QQ截图20200513171135](https://user-images.githubusercontent.com/54163593/81794185-fc330580-953c-11ea-81d0-0492de43d7f6.png)
![QQ截图20200513171145](https://user-images.githubusercontent.com/54163593/81794188-fd643280-953c-11ea-84a3-d74d50536be9.png)

**Comment by Gxy-2001** [comment]
老哥，我不知道具体的原因，但是你可以debug一下这几行代码具体执行时都是什么，是不是正确的路径，我自己是这样写的
![image](https://user-images.githubusercontent.com/56917631/81796814-892b8e00-9540-11ea-9f0b-eb1c5d950638.png)

**Comment by wym0120** [comment]
我们不负责处理业务逻辑的bug。
我们不负责处理业务逻辑的bug。
我们不负责处理业务逻辑的bug。

建议再去读一遍生存指南。
建议再去读一遍生存指南。
建议再去读一遍生存指南。

关于这个bug我能给的提示是你去看一下BufferUnderflowException这个异常的API，它里面写了实在什么情况会抛出来，你在对着这个去找你的代码里是否出现了对应的情况。
