### ISSUE TITLE
本地出现这个NoClassDefFoundError，但是oj上可以通过

### ISSUE THREAD

**Issue by RubiscoQAQ** [XZ-X/2020SE1-FAQ#9]
![image](https://user-images.githubusercontent.com/65221124/81809449-fbf23480-9553-11ea-847c-fa60b923833e.jpeg)

**Comment by XZ-X** [comment]
maven依赖导入正确吗？如果不正确的话参见一下之前的maven相关的issue

**Comment by RubiscoQAQ** [comment]
> maven依赖导入正确吗？如果不正确的话参见一下之前的maven相关的issue

![Uploading 81822782...]()
现在是这个报错，是ide出问题了吗

**Comment by wym0120** [comment]
你这个图是不是挂掉了...一般来说这个问题出在maven，你重新导入一下项目或者到设置里面对maven enable auto-import试试。OJ能过是因为OJ的maven配置没有问题

**Comment by RubiscoQAQ** [comment]
> 你这个图是不是挂掉了...一般来说这个问题出在maven，你重新导入一下项目或者到设置里面对maven enable auto-import试试。OJ能过是因为OJ的maven配置没有问题

好的，已经解决啦
好像reimport还要看时机😂
有的时候会失败哈哈哈
